server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5432/shareit
spring.datasource.username=test
spring.datasource.password=test
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.profiles.test:
datasource.url=jdbc:h2:mem:shareit
datasource.driver-class-name=org.h2.Driver
datasource.username=sa
datasource.password=
jpa.database-platform=org.hibernate.dialect.H2Dialect
jpa.hibernate.ddl-auto=create
jpa.show-sql=true
jpa.properties.hibernate.format_sql=true
h2.console.enabled=true
h2.console.path=/h2-console
spring.sql.init.mode=never
logging.level.org.springframework.orm.jpa=INFO
logging.level.org.springframework.transaction=INFO
logging.level.org.springframework.transaction.interceptor=TRACE
logging.level.org.springframework.orm.jpa.JpaTransactionManager=DEBUG
spring.profiles.active=test

