create table if not exists users
(
    user_id    bigint generated by default as identity primary key,
    user_name  varchar(200) not null,
    user_email varchar(200) not null,
    CONSTRAINT user_name_not_empty CHECK (user_name <> ''),
    CONSTRAINT user_email_not_empty CHECK (user_email <> ''),
    CONSTRAINT user_email_unique UNIQUE (user_email)
);

create table if not exists items
(
    item_id          bigint generated by default as identity primary key,
    item_name        varchar(200) not null,
    item_description varchar(1000) not null,
    is_available     boolean not null,
    owner_id         bigint references users (user_id) on delete cascade not null,
    request_id       bigint,
    CONSTRAINT item_name_not_empty CHECK (item_name <> ''),
    CONSTRAINT item_description_not_empty CHECK (item_description <> '')
);

create table if not exists bookings
(
    booking_id bigint generated by default as identity primary key,
    start_date timestamp without time zone not null,
    end_date   timestamp without time zone not null,
    item_id    bigint references items (item_id) on delete cascade not null,
    booker_id  bigint references users (user_id) on delete cascade not null,
    status     int not null,
    CONSTRAINT end_is_after_start CHECK (end_date > start_date)
);

create table if not exists requests
(
    request_id          bigint generated by default as identity primary key,
    request_description varchar(1000),
    requestor_id        bigint references users (user_id) on delete cascade not null
);

create table if not exists comments
(
    comment_id bigint generated by default as identity primary key,
    text        varchar(2000) not null,
    item_id     bigint references items (item_id) on delete cascade not null,
    author_id    bigint references users (user_id) on delete cascade not null,
    created timestamp without time zone not null,
    CONSTRAINT text_is_not_empty CHECK (text <> '')
);